import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* NavBar     */}
      <nav className={styles.mainnav}>
        <ul className={styles.u}>
          <Link href='/'><li>Home</li></Link>
          <Link href='/blogs'><li>Blogs</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/contact'><li>Contact Us</li></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>
        <div className={styles.description}>
          <p>
            By a hunting coder
          </p>
        </div>

        <div className={styles.blogs}>
          <div className={styles.blogItem}>
            <h1>How to learn Javascript in 2023?</h1>
            <p>Javascript is the language used to design the logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h1>How to learn Javascript in 2023?</h1>
            <p>Javascript is the language used to design the logic for the web</p>
          </div>
        </div>
      </main>
    </>
  )
}
